AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - vendor/**/*
    - tmp/**/*
    - pkg/*
    - examples/**/*.rb

Layout/LineLength:
  Max: 180

Style/SymbolArray:
  EnforcedStyle: brackets

Style/Lambda:
  EnforcedStyle: literal

Naming/MethodParameterName:
  AllowedNames:
    - id
    - cb
    - fd

Naming/AccessorMethodName:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

